services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-service
    ports:
      - "8080:8080"
    depends_on:
      - db
      - valkey
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_URL=jdbc:postgresql://db:5432/bankdb
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
      - SPRING_DATA_REDIS_HOST=valkey
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=bankservice
      - SPRING_RABBITMQ_PASSWORD=password
      - SPRING_RABBITMQ_VIRTUAL_HOST=bankservice
      - TRANSACTION_POINT_URL=http://host.docker.internal:8081
      - TRANSACTION_POINT_TOKEN_URL=http://host.docker.internal:8081/oauth/token
      - TRANSACTION_POINT_CLIENT_ID=client-id
      - TRANSACTION_POINT_CLIENT_SECRET=client-secret
      - TRANSACTION_POINT_CLIENT_SCOPE=scope

  db:
    image: postgres:17-alpine
    container_name: bank-service-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bankdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:8.0-alpine
    container_name: bank-service-valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    command: valkey-server --appendonly yes

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: bank-service-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=bankservice
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=bankservice
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  valkey_data:
  rabbitmq_data:
