name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: wrapper

    - name: Run tests
      run: |
        ./gradlew test jacocoTestReport \
          --parallel \
          --build-cache \
          --configuration-cache \
          --continue
      env:
        SPRING_PROFILES_ACTIVE: test

    - name: Debug test results
      if: always()
      run: |
        echo "=== Test Results Directory Structure ==="
        find build/test-results -name "*.xml" -type f 2>/dev/null || echo "No XML files found"
        echo "=== All files in build/test-results ==="
        find build/test-results -type f 2>/dev/null || echo "No files found in build/test-results"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: build/test-results/
        retention-days: 7

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: 'build/test-results/**/*.xml'
        reporter: java-junit
        fail-on-error: false
        fail-on-empty: false

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: |
          build/reports/jacoco/test/html/
          build/reports/jacoco/test/jacocoTestReport.xml
        retention-days: 7

    # TODO: Re-enable quality checks after fixing configuration issues
    # - Detekt: Update config for version compatibility
    # - SpotBugs: Fix verification failures  
    # - ktlint: Fix formatting violations in build.gradle.kts